import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./css/globals.css";
import { ThemeModeScript, ThemeProvider } from 'flowbite-react';
import customTheme from "@/ultils/theme/custom-theme";
import Navbar from "./components/homePage/navBar";
import Footer from "./components/homePage/Footer";



const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OneLink Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/assets/favicon-new.png"
          type="image/png"
          sizes="32x20"
        />
        <ThemeModeScript />
        <link
          href="https://fonts.googleapis.com/css2?family=Archivo+Expanded:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>

      {/* THAY ĐỔI Ở ĐÂY: Thêm 'overflow-x-hidden'
      */}
      <body className={`${plus_jakarta_sans.className} overflow-x-hidden`}>
        <ThemeProvider theme={customTheme}>
          <Navbar />
          <main className="pt-20">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}