import React from "react";
import type { Metadata } from "next";
import "../css/globals.css";



export const metadata: Metadata = {
  title: "OneLink Marketing",
  description: "Generated by create next app",
};

export default function ServiceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="service-layout">
      {children}
    </section>
  );
}

